### ISSUE TITLE
Support of Multiple Queries

### ISSUE THREAD

**Issue by ITsvetkoFF** [VictoriaMetrics/vmui#11]
Nice to have:
- many queries in on graph

**Comment by valyala** [comment]
FYI, vmui source code has been embedded into VictoriaMetrics - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1413), so further development should take place at https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui .

Closing this issue. Feel free re-creating it at [the main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).
