### ISSUE TITLE
sort results for instance query as json

### ISSUE THREAD

**Issue by freeseacher** [VictoriaMetrics/vmui#17]
someone should sort results, so they can be reproducable across launches within 15s interval

**Comment by valyala** [comment]
FYI, vmui source code has been embedded into VictoriaMetrics - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1413), so further development should take place at https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui .

Closing this issue. Feel free re-creating it at [the main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).
