### ISSUE TITLE
MuiTooltip-popper for "Auth Settings" icon

### ISSUE THREAD

**Issue by denisgolius** [VictoriaMetrics/vmui#33]
Need to add `MuiTooltip-popper` with explanation what this button do like it was made for `Execute Query` button.

![creencast](https://user-images.githubusercontent.com/5650611/113013323-4b4d4d80-9184-11eb-89c2-bdc6c7a45e69.gif)

**Comment by valyala** [comment]
FYI, vmui source code has been embedded into VictoriaMetrics - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1413), so further development should take place at https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui .

Closing this issue. Feel free re-creating it at [the main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).
