### ISSUE TITLE
Layout error on big query

### ISSUE THREAD

**Issue by kevinvirs** [VictoriaMetrics/vmui#35]
**Describe the bug**
If query have more 27 rows, fully hiding graph with results, wihout scrollbar on all tabs chart/json/table

**To Reproduce**
display dimension 1366x768
add any big query or insert empty rows

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/47024525/118494298-346eb480-b74c-11eb-847a-a03a599d5166.png)

**Comment by valyala** [comment]
FYI, vmui source code has been embedded into VictoriaMetrics - see [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1413), so further development should take place at https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmui .

Closing this issue. Feel free re-creating it at [the main VictoriaMetrics repository](https://github.com/VictoriaMetrics/VictoriaMetrics/issues).
