### ISSUE TITLE
Query arguments are not made URL-safe

### ISSUE THREAD

**Issue by steersbob** [VictoriaMetrics/vmui#37]
When using a query that contains URI-query reserved characters, the page fails to load, and a `Uncaught URIError: URI malformed` is shown in console.

The query is
```
{__name__="humidity/humidity[%]"}
```

The resulting url is:
```
http://manyberry.local/victoria/vmui/?serverUrl=http://manyberry.local/victoria&displayType=chart&query={__name__=%22humidity/humidity[%]%22}&time[duration]=1d&time[period][start]=1626531592.028&time[period][end]=1626617992.028&time[period][step]=2880&queryControls[autoRefresh]=false
```

It appears the % character in `humidity/humidity[%]` is not escaped.

Sanitizing the query itself to `{__name__="humidity/humidity[%25]"}` does not cause an error, but does not yield data either.

**Comment by valyala** [comment]
The issue should be fixed in [the latest release](https://docs.victoriametrics.com/CHANGELOG.html) of `vmui`, which is built into VictoriaMetrics - see [these docs](https://docs.victoriametrics.com/#vmui) for details.
